// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRTU-q_YOU89DAlKhK263dEFG0-SoiKq0',
    appId: '1:548268582266:web:645c86176d0a0ae4fd62c3',
    messagingSenderId: '548268582266',
    projectId: 'pizza-app-delivery-50376',
    authDomain: 'pizza-app-delivery-50376.firebaseapp.com',
    storageBucket: 'pizza-app-delivery-50376.firebasestorage.app',
    measurementId: 'G-4R1YFYG9KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfchfcX0T0TfQ4km4XJVLbE-sXy6XB0_c',
    appId: '1:548268582266:android:2ff6901d0cba4635fd62c3',
    messagingSenderId: '548268582266',
    projectId: 'pizza-app-delivery-50376',
    storageBucket: 'pizza-app-delivery-50376.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIzH9pFqpY5yORuLxATuGQHEwax3DWxY0',
    appId: '1:548268582266:ios:23305260162198d7fd62c3',
    messagingSenderId: '548268582266',
    projectId: 'pizza-app-delivery-50376',
    storageBucket: 'pizza-app-delivery-50376.firebasestorage.app',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIzH9pFqpY5yORuLxATuGQHEwax3DWxY0',
    appId: '1:548268582266:ios:23305260162198d7fd62c3',
    messagingSenderId: '548268582266',
    projectId: 'pizza-app-delivery-50376',
    storageBucket: 'pizza-app-delivery-50376.firebasestorage.app',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRTU-q_YOU89DAlKhK263dEFG0-SoiKq0',
    appId: '1:548268582266:web:ed9e7d1816f755a8fd62c3',
    messagingSenderId: '548268582266',
    projectId: 'pizza-app-delivery-50376',
    authDomain: 'pizza-app-delivery-50376.firebaseapp.com',
    storageBucket: 'pizza-app-delivery-50376.firebasestorage.app',
    measurementId: 'G-GB9DFGH4J8',
  );
}
